config/routes.rb
Rails.application.routes.draw do
  get 'admin/messaging_index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'static_pages#home'
  get 'messages' => 'messages#index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'sessions/new'
  resources :users
  resources :messages
  resources :conversations
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
  validates :content, presence: true
  scope :for_display, -> { order(:created_at).last(50)}
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_many :messages
  has_many :conversations
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}

  class << self
    # Returns the hash digest of the given string.
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  before_action do
    is_admin
    # :my_conversations
    # @friend = User.find(@conversation.sender_id)
    # @other = User.find(@conversation.recipient_id)
    # @me = User.find(current_user.id)
  end

  def index
    @user = User.find(current_user.id)
    @users = User.all
    @conversations = Conversation.all
  end

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
    redirect_to conversation_messages_path(@conversation)
  end

  def show
    @conversation = Conversation.find(params[:id])
    @message = @conversation.messages.new
  end

  private
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end

  def my_conversations
    if @me.id != @conversation.sender_id || @me.id != @conversation.recipient_id
      redirect_to(users_url)
    end
  end

  def is_admin
    if current_user.admin?
      return
    else
      redirect_to '/404.html'
    end
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :get_messages

  def index
  end

  def create
    unless current_user.admin
      @conversation = current_user.conversations.last
      message = @conversation.messages.build(message_params)
      message.user_id = current_user.id
      message.save

      if @conversation.messages.count == 1
        ActionCable.server.broadcast 'room_channel',
                activated: true,
                content:  message.content,
                user: current_user.id,
                conversation: @conversation.id,
                username: current_user.username
      else
        ActionCable.server.broadcast 'room_channel',
                content:  message.content,
                user: current_user.id,
                conversation: @conversation.id,
                username: current_user.username
      end
    else
      @conversation = Conversation.find(params[:conversation_id])
      message = @conversation.messages.build(message_params)
      message.user_id = current_user.id
      if message.save
        ActionCable.server.broadcast 'room_channel',
          content:  message.content,
          user: current_user.id,
          conversation: @conversation.id,
          username: current_user.username
      end
    end
  end

  private

    def get_messages
      @messages = Message.for_display
      @message  = current_user.messages.build
    end

    def message_params
      params.require(:message).permit(:content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to conversations_path
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      if current_user.admin
        redirect_to conversations_url
        return
      else
        @conversation = current_user.conversations.last
      end
    else
      @user = User.new
      @user.username = 'Usted'
      @user.password = 'password'
      @user.password_confirmation = 'password'
      @user.save
      log_in(@user)
      remember(@user)
      @conversation = @user.conversations.new
      @conversation.online = true
      @conversation.save
    end
    @message = @conversation.messages.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

      # Returns true if the given user is the current user.
    def current_user?(user)
        user == current_user
    end

    def current_user
        if session[:user_id]
          @current_user ||= User.find_by(id: session[:user_id])
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end

      # Redirects to stored location (or to the default).
    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end

  # Stores the URL trying to be accessed.
    def store_location
        session[:forwarding_url] = request.original_url if request.get?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/_footer.html.erb
<footer class="footer" data-background-color="black">
  <div class="container">
    <nav>
      <ul>
        <li>
          <a href="http://mailto:activadospanama.org">
            Contáctanos
          </a>
        </li>
        <li>
          <a href="http://activadospanama.com/?page_id=29">
            Noticias
          </a>
        </li>
      </ul>
    </nav>
    <div class="copyright" id="copyright">
      &copy; <a href="https://www.kblack.design">Kblack Design</a>
      <script>
        document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))
      </script>
    </div>
  </div>
</footer>

app/views/conversations/_show.html.erb
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>
<div class="message">
  <div id="messages" class="messages">
    <div class="messages-table">
    <%= tag.div id: @conversation.id do%>
      <div class="message">
        <div class = "message-user">Admin:</div>
        <div class= "message-content">¿En qué puedo ayudarte?</div>
      </div>
      <% if @conversation.messages.any? %>
        <% @conversation.messages.each do |m| %>
          <div class="message">
            <%= render m %>
          </div>
        <% end %>
      <% end %>
    <% end %>
    </div>
  </div>
</div>
<%= render 'messages/message_form' %>

app/views/conversations/index.html.erb
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>
<body class="profile-page sidebar-collapse">
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg bg-primary fixed-top navbar-transparent " color-on-scroll="400">
    <div class="container">
      <div class="dropdown button-dropdown">
        <a href="#pablo" class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown">
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-header">Dropdown header</a>
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Separated link</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">One more separated link</a>
        </div>
      </div>
      <div class="navbar-translate">
        <a class="navbar-brand" rel="tooltip" data-placement="bottom" target="_blank">
          Activados
        </a>
        <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-bar top-bar"></span>
          <span class="navbar-toggler-bar middle-bar"></span>
          <span class="navbar-toggler-bar bottom-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse justify-content-end" id="navigation" data-nav-image="../assets/img/blurred-image-1.jpg">
        <ul class="navbar-nav">
          <li class="nav-item">
          </li>
          <li class="nav-item">
            <a class="nav-link" rel="tooltip" title="Siguenos en Twitter" data-placement="bottom" href="#" target="_blank">
              <i class="fab fa-twitter"></i>
              <p class="d-lg-none d-xl-none">Twitter</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" rel="tooltip" title="Danos un me gusta en Facebook" data-placement="bottom" href="http://elvenezolano.com.pa/activados-panama-dicto-la-charla-migracion-inteligente/?fbclid=IwAR293cTuUkSwjHClvUZQzYS1hvp1YyfRitAhHxGTT_Q_YlFpWO66tllmIjg" target="_blank">
              <i class="fab fa-facebook-square"></i>
              <p class="d-lg-none d-xl-none">Facebook</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" rel="tooltip" title="Siguenos en Instagram" data-placement="bottom" href="https://www.instagram.com/activadospanama/" target="_blank">
              <i class="fab fa-instagram"></i>
              <p class="d-lg-none d-xl-none">Instagram</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- End Navbar -->
  <div class="wrapper">
    <div class="page-header clear-filter" filter-color="orange">
      <div class="page-header-image" data-parallax="true" style="background-image:url('https://scontent-hkg3-1.xx.fbcdn.net/v/t1.0-9/20294124_10156125334525476_3887029046877520143_n.jpg?_nc_cat=109&_nc_ht=scontent-hkg3-1.xx&oh=19467d4009b008c66660e0f68ceddfba&oe=5D3404CE');">
      </div>
      <div class="container">
        <h3 class="title"><%="Admin"%></h3>
      </div>
    </div>
    <div class="section">
      <div class="container">
        <div class="button-container">
          <a href="#button" class="btn btn-primary btn-round btn-lg">Chats</a>
        </div>
        <h3 class="title">Chats</h3>
        <div class="progress-container" id="liveChats">
          <% @conversations.sort.reverse_each do |conversation| %>
            <%if conversation.user_id != current_user.id%>
              <% if conversation.online %>
                <%= link_to conversation.id, conversation_path(conversation), class: "btn btn-primary btn-round btn-lg", id: "conversation"+conversation.id.to_s%>
              <%else %>
                <%= link_to conversation.id, conversation_path(conversation), class: "btn btn-secondary btn-round btn-lg", id: "conversation"+conversation.id.to_s %>
              <% end %>
            <%end%>
          <% end %>
        </div>
        <div class="row">
          <div class="col-md-6 ml-auto mr-auto">
          </div>
        </div>
      </div>
    </div>
    <footer class="footer footer-default">
      <div class="container">
        <nav>
          <ul>
            <li>
              <a href="http://mailto:activadospanama.org">
                Contáctanos
              </a>
            </li>
            <li>
              <a href="http://activadospanama.com/?page_id=29">
                Noticias
              </a>
            </li>
          </ul>
        </nav>
        <div class="copyright" id="copyright">
          &copy;
          <script>
            document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))
          </script>,
          <a href="https://www.kblack.design" target="_blank">Kblack Design</a>.
        </div>
      </div>
    </footer>
  </div>
  <div class="sidebar-floating collapse collapse" id="floating-chat" style="">
    <div class="sidebar-content">
        <div class="chat-module" data-filter-list="chat-module-body">
            <div class="chat-module-top">
                <form>
                    <div class="input-group input-group-round">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <i class="material-icons"></i>
                            </span>
                        </div>
                        <input type="search" class="form-control filter-list-input" placeholder="Search chat" aria-label="Search Chat" aria-describedby="search-chat">
                    </div>
                </form>
                    <div class="chat-module-body filter-list-1540911837798 filter-list-1544176316151" id="messages-table"><div class="media chat-item">
                    </div></div>
            </div>
            <div class="chat-module-bottom">
                <form class="chat-form" id="new_message" action="/messages" accept-charset="UTF-8" data-remote="true" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="authenticity_token" value="lMStlod5QTCmuSNu1mAFi2IG+GoIqvg2O5Rl3j8t8+dKnftQAdNkdPmIf+XDYfSohnBtnxze2F1bWDl2y5DMbQ==">
                <input value="12" type="hidden" name="message[micropost_id]" id="message_micropost_id">
                <input value="1" type="hidden" name="message[user_id]" id="message_user_id">
                <textarea class="form-control" placeholder="Type message" rows="1" style="overflow: hidden; overflow-wrap: break-word; resize: none; height: 40px;" data-textarea="body" name="message[body]" id="message_body"></textarea>

                <input type="submit" name="commit" value="Send" style="display: none;" id="chat-send" data-disable-with="Send">
            </form>
            </div>
        </div>
    </div>
</div>
  <!--   Core JS Files   -->

app/views/conversations/index_copy.html.erb
<div class="ui segment">
  <h3 id='mailbox_header'>Mailbox</h3>

  <div class="ui list" id='mail_list'>
    <div class="item">
      <% @conversations.each do |conversation| %>
          <%= link_to conversation.id, conversation_path(conversation) %>
      <% end %>
    </div>
  </div>
</div>

app/views/conversations/show.html.erb
<%unless current_user.admin %>
<%= render 'messages/message_form' %>
<div class="modal fade modal-mini modal-primary" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header justify-content-center">
        <h2>Chat en Vivo</h2>
      </div>
      <div class="modal-body">
        <%= render 'conversations/show', conversation_id: @conversation.id %>
      </div>
    </div>
  </div>
</div>
<%else%>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header justify-content-center">
        <h2>Chat en Vivo</h2>
      </div>
      <div class="modal-body">
        <%= render 'conversations/show', conversation_id: @conversation.id %>
      </div>
    </div>
  </div>
  <div id="announcements">
  </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="/assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="/assets/img/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="description" content="Activados Panamá facilita el proceso de inmigrar de venezuela a Panamá.">
  <title>
    Activados Panamá | Inmigración de Venezuela a Panamá
  </title>
  <meta name="author" content="Kenton Blacutt">
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <!-- CSS Files -->
  <link href="/assets/css/bootstrap.min.css" rel="stylesheet" />
  <link href="/assets/css/now-ui-kit.css?v=1.2.0" rel="stylesheet" />
  <link href="/assets/demo/demo.css" rel="stylesheet" />
</head>

  <%=yield%>


  <!--   Core JS Files   -->
  <script src="/assets/js/core/jquery.min.js" type="text/javascript"></script>
  <script src="/assets/js/core/popper.min.js" type="text/javascript"></script>
  <script src="/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
  <!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
  <script src="/assets/js/plugins/bootstrap-switch.js"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="/assets/js/plugins/nouislider.min.js" type="text/javascript"></script>
  <!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
  <script src="/assets/js/plugins/bootstrap-datepicker.js" type="text/javascript"></script>
  <!--  Google Maps Plugin    -->
  <!-- Control Center for Now Ui Kit: parallax effects, scripts for the example pages etc -->
  <script src="/assets/js/now-ui-kit.js?v=1.2.0" type="text/javascript"></script>
  <script>
    $(document).ready(function() {
      // the body of this function is in assets/js/now-ui-kit.js
      nowuiKit.initSliders();
    });

    function scrollToDownload() {

      if ($('.section-download').length != 0) {
        $("html, body").animate({
          scrollTop: $('.section-download').offset().top
        }, 1000);
      }
    }
  </script>


</html>

app/views/messages/_index.html.erb
<%= csrf_meta_tags%>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>
<div class="message">
  <div class="messages-table">
  <%= render 'messages/messages' %>
  <%= render 'messages/message_form' %>
</div>

app/views/messages/_message.html.erb
<%if message.id? %>
  <div class="message-user">
    <%=message.user.username+":" %>
  </div>
<%end%>
<div class="message-content">
  <%= message.content %>
</div>

app/views/messages/_message_form.html.erb
<div class="message-input">
  <%= form_for(@message, remote: true) do |f| %>
    <%= f.text_area :content %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token%>
    <%= hidden_field_tag :conversation_id, @message.conversation.id%>
    <%= f.submit "Send", :style => 'display: none'%>
  <% end %>
</div>

app/views/messages/_messages.html.erb
<div id="messages" class="messages">
  <div id="messages-table" class="messages-table">
    <% if @messages.any? %>
      <%= render @messages %>
    <% end %>
  </div>
</div>

app/views/messages/index.html.erb
<%= csrf_meta_tags%>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>
<div class="message-wr">
  <%= render 'messages' %>
  <%= render 'message_form' %>
</div>

app/views/static_pages/_footer.html.erb
<footer class="footer" data-background-color="black">
  <div class="container">
    <nav>
      <ul>
        <li>
          <a href="mailto:contactanos@activados.org">
            Contáctanos
          </a>
        </li>
        <li>
          <a href="http://activadospanama.com/?page_id=29">
            Noticias
          </a>
        </li>
      </ul>
    </nav>
    <div class="copyright" id="copyright">
      &copy; <a href="https://www.kblack.design">Kblack Design</a>
      <script>
        document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))
      </script>
    </div>
  </div>
</footer>